# Generated by Django 4.1.7 on 2023-03-13 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Product Title')),
                ('slug', models.SlugField(max_length=160, verbose_name='Product slug')),
                ('description', models.TextField(verbose_name='Short Description')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Product image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('productStock', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(verbose_name='Is Active')),
                ('is_featured', models.BooleanField(verbose_name='Is Featured')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category', verbose_name='product_category')),
            ],
        ),
    ]
