# Generated by Django 4.1.7 on 2023-03-17 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatedimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='relimg')),
                ('products', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
